apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abrumley-mw/argocd.git
    targetRevision: HEAD
    path: apps/blue
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd