apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-apps
  namespace: argocd
spec:
  project: default
  source:
    #repoURL: https://github.com/abrumley-mw/argocd-blue.git
    repoURL: https://github.com/abrumley-mw/argocd.git
    targetRevision: HEAD
    path: blue
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd