apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue
  namespace: argocd
spec:
  project: blue
  source:
    repoURL: git@github.com:abrumley-mw/argocd-blue.git
    targetRevision: HEAD
    path: blue
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: blue