apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:abrumley-mw/argocd-green.git
    targetRevision: HEAD
    path: green
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd